<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <MvcRazorCompileOnPublish>true</MvcRazorCompileOnPublish>
    <UserSecretsId>aspnet-WebAppNetCore-DFA876CE-A654-47E1-8633-5083DF8F5376</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HtmlAgilityPack" Version="1.11.71" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="10.0.12" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="10.0.2" PrivateAssets="All" />
    <!-- Override the scaffolding dependency affected by GHSA-g4vj-cjjj-v7hg. -->
    <PackageReference Include="NuGet.Protocol" Version="6.12.5" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="Views\Account\RPIFrame.cshtml">
      <Pack>$(IncludeRazorContentInPack)</Pack>
    </Content>
    <Content Update="Views\Account\ReauthenticationCallBack.cshtml">
      <Pack>$(IncludeRazorContentInPack)</Pack>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Script\" />
  </ItemGroup>

</Project>
